import { type NextPage } from "next";
import Head from "next/head";
// import ContactSection from "../sections/ContactSection";
import { IntroSection } from "../sections/IntroSection";
import { ProjectSection } from "../sections/ProjectSection";
import { StatSection } from "../sections/StatSection";
import { SkillSection } from "../sections/SkillSection";
import { TestimonialSection } from "../sections/TestimonialSection";
// import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  // const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Welcome to my Personal Website</title>
        {/* <meta name="description" content="Generated by create-t3-app" /> */}
      </Head>
      <a href="https://github.com/TaipeiDev/portfolio-t3">
        <img
          decoding="async"
          loading="lazy"
          width="149"
          height="149"
          src="https://github.blog/wp-content/uploads/2008/12/forkme_right_red_aa0000.png?resize=149%2C149"
          className="attachment-full size-full"
          alt="Fork me on GitHub"
          data-recalc-dims="1"
          style={{ position: "absolute", top: 0, right: 0 }}
        />
      </a>
      <main className="bg-white text-slate-700">
        <IntroSection />
        <SkillSection />
        <StatSection />
        <ProjectSection />
        <TestimonialSection />
        {/* <ContactSection /> */}
      </main>
    </>
  );
};

Home.getInitialProps = async ({}) => {
  return {};
};

export default Home;
